---
window:
  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true
  opacity: 0.92
  option_as_alt: OnlyLeft
font:
  normal:
    family: Hack Nerd Font
  size: 12
use_thin_strokes: true
draw_bold_text_with_bright_colors: true
schemes:
  gruvbox_material: &gruvbox_material
    primary:
      background: "0x1d2021"
      foreground: "0xd4be98"
    normal:
      black: "0x32302f"
      red: "0xea6962"
      green: "0xa9b665"
      yellow: "0xd8a657"
      blue: "0x7daea3"
      magenta: "0xd3869b"
      cyan: "0x89b482"
      white: "0xd4be98"
    bright:
      black: "0x32302f"
      red: "0xea6962"
      green: "0xa9b665"
      yellow: "0xd8a657"
      blue: "0x7daea3"
      magenta: "0xd3869b"
      cyan: "0x89b482"
      white: "0xd4be98"
  nordfox: &nordfox
    primary:
      background: "0x191d24"
      foreground: "0xcdcecf"
    # Normal colors
    normal:
      black: "0x3b4252"
      red: "0xbf616a"
      green: "0xa3be8c"
      yellow: "0xebcb8b"
      blue: "0x81a1c1"
      magenta: "0xb48ead"
      cyan: "0x88c0d0"
      white: "0xe5e9f0"
    # Bright colors
    bright:
      black: "0x465780"
      red: "0xd06f79"
      green: "0xb1d196"
      yellow: "0xf0d399"
      blue: "0x8cafd2"
      magenta: "0xc895bf"
      cyan: "0x93ccdc"
      white: "0xe7ecf4"
    indexed_colors:
      - { index: 16, color: "0xc9826b" }
      - { index: 17, color: "0xbf88bc" }
colors: *gruvbox_material
cursor:
  style:
    shape: Block
    blinking: Never
mouse:
  hide_when_typing: true
