---
session: frankenrepo
root: ~/coding/frankenrepo/
windows:
  - name: dev
    layout: main-horizontal
    commands:
      - clear
  - name: sh
    layout: main-horizontal
    commands:
      - clear
