---
session: frankenrepo.dev
root: ~/coding/frankenrepo.dev/
windows:
  - name: dev
    layout: main-horizontal
    commands:
      - clear
  - name: sh
    layout: main-horizontal
    commands:
      - clear
  - name: server
    layout: main-horizontal
    commands:
      - npm run dev
