---
session: hedispp
root: ~/coding/hedispp/
windows:
  - name: dev
    layout: main-horizontal
    commands:
      - clear
  - name: hedisc
    root: ../hedis_c
    layout: main-horizontal
    commands:
      - clear
  - name: fosite
    root: ../fosite
    layout: main-horizontal
    commands:
      - clear
  - name: sh
    layout: main-horizontal
    commands:
      - clear
