---
session: planning
root: ~/work/planning
windows:
  - name: dev
    root: .
    layout: main-horizontal
    commands:
      - clear
  - name: sh
    layout: main-horizontal
    commands:
      - clear
  - name: notes
    layout: main-horizontal
    root: ~/MEGA/notes
    commands:
      - nvim
  - name: moco
    layout: main-horizontal
    root: ../MocoTrackingClient/
    commands:
      - poetry run python moco_client.py
