#!/usr/bin/env sh

setxkbmap us
if [ "$(cat /etc/hostname)" = "moebius" ]; then
    xrandr --output DisplayPort-2 --mode 3440x1440 --rate 120
fi

pgrep -x sxhkd >/dev/null || sxhkd &
pkill picom
picom -b --experimental-backends
feh --bg-fill /home/tommy/wallpapers/misc/tomek-pietrzyk-imp-bike-tomek-pietrzyk-3.jpg
/home/tommy/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
