if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

if [ "$(cat /etc/hostname)" = "moebius" ]; then
    xrandr --output DisplayPort-2 --mode 3440x1440 --rate 120
fi

setxkbmap us
picom -fb --experimental-backends --backend glx
exec bspwm
