#!/usr/bin/env sh
logfile="$HOME/.dkrc.log"
[ -d "$HOME/.local/share/xorg" ] && logfile="$HOME/.local/share/xorg/dkrc.log"
: >"$logfile"

setxkbmap us
if [ "$(cat /etc/hostname)" = "moebius" ]; then
    xrandr --output DisplayPort-2 --mode 3440x1440 --rate 120
fi

dunst &
# pgrep -x sxhkd >/dev/null || sxhkd -c "$HOME/.config/dk/sxhkdrc" &
pgrep -x sxhkd >/dev/null || sxhkd &
pkill picom
picom -b --experimental-backends
gammastep -l 54.0:10.0 &
feh --bg-fill /home/tommy/wallpapers/gruvbox/lofi-cafe_gray.jpg
/home/tommy/.config/polybar/launch.sh

if [ "$(cat /etc/hostname)" = "moebius" ]; then
    xrandr --output DisplayPort-2 --mode 3440x1440 --rate 120
fi

border_width=2
border_outer_width=0

{
    dkcmd set numws=6
    dkcmd set ws=1 name="dev"
    dkcmd set ws=2 name="web"
    dkcmd set ws=3 name="misc"
    dkcmd set ws=4 name="launchers"
    dkcmd set ws=5 name="games"
    dkcmd set ws=6 name="comms"

    # default layout
    dkcmd set ws=_ apply layout=rtile master=1 stack=4 gap=8 msplit=0.66

    dkcmd set focus_open=true focus_mouse=true
    dkcmd set mouse mod=super move=button1 resize=button3

    dkcmd set border width=$border_width outer_width=$border_outer_width \
        colour \
        focus='#d8a657' \
        unfocus='#5a524c' \
        urgent='#ea6962'

    dkcmd rule class="^gimp$" ws=3
    dkcmd rule class="^(pavucontrol|transmission-gtk|lxappearance)$" float=true
    dkcmd rule title="^(Picture in picture|Picture-in-picture)$" float=true stick=true
    dkcmd rule class="^(steam|lutris|battle.net.exe)$" float=true ws=4
    dkcmd rule title="^(Wine System Tray)$" float=true ws=4 x=3250 y=1350

    dkcmd rule apply '*' # reapplies rules on dk restart
} >>"$logfile" 2>&1

if grep -q 'error:' "$logfile"; then
    hash notify-send && notify-send -t 0 -u critical "dkrc has errors" \
        "$(awk '/error:/ {sub(/^error: /, ""); gsub(/</, "\<"); print)' "$logfile")"
    exit 1
fi

exit 0
